# Generated by Django 3.1.6 on 2021-02-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_booking_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='zip_code',
        ),
    ]
