# Generated by Django 3.1.6 on 2021-02-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_bookingupdate_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingupdate',
            name='room_no',
        ),
    ]
